### PR TITLE
minor: rm trailing white spaces

### PR DESCRIPTION
**Pull request by CeresBarros**
suggestion (if PR is accepted ;) ): if using RStudio make sure the option of removing white spaces and empty lines is active.

### CODE REVIEW

**Review by achubaty — CHANGES_REQUESTED** [review]
can you make that change in the Rproj file and make sure it's commited to git (i.e., not in gitignore) so everyone gets it?

**Comment by CeresBarros** [comment]
done :)

**Comment by achubaty** [comment]
pushed? not showing up here

**Comment by CeresBarros** [comment]
I did push, how strange... Tried again now

**Pull request merged**
